name: get_secret

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show encrypted_secret_value with base64 encoding
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        run: |
          echo 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lVRmlqbE5UeTFlOW92MmVPU2lQeDl6aFZ2ZWc0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0FEQWVGdzB5TlRBM01EUXdPRE00TlRaYUZ3MHlOVEE0TURNd09ETTROVFphTUFBd2dnRWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQnJ5eVFBY2liYzdoYVpZbTdNQXhpVWZMZERrc3hOcDlDCmtNWnBkNko2RnkzMEZ6WUxOK2RWK2pCcG9rN2s5MldqNDZNdEV4dGVTRDBNclJqdVExMEZ1U2FCZlRmY1MreU8KTjUyV0s4aGhocmQ0NzFITTBFWnlHeTBzUjJjVHlVbFlNTEV4NFNLcG5tTk8xd25hRFFmc3d1VnJFMVBzbGFVYQo5OFBrRTMyTzB5YTBXL2pZdGNSUlRnMTlacklJVkxFNmc5YjczZDVqbTFOZHRsY1JvZTNjejcrNnJqcGgxL0VNCmFuZzE0bGZzcHgzZk42YUVzQWZxTFZzcDhoNUtZOEl2VEZTZjh6YWxWU0ZhbGo5U3lPRUJncHVOMWphSHFzb3cKcXFnUytxZWQ0MmwrRUMzY3Z2NEEyZ0I3L2FPVzlOTjZZdVdkWjJLaVRpQnZnWWZSSUJmdkFnTUJBQUdqVXpCUgpNQjBHQTFVZERnUVdCQlRrR29xVzRSdS9FZlRHUSttQkE4eUVDdEtuQ1RBZkJnTlZIU01FR0RBV2dCVGtHb3FXCjRSdS9FZlRHUSttQkE4eUVDdEtuQ1RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQ2xjdXZPdHUxYUVpL3JtL0t0eTUwbENKcHV3Q29yQSs3U0Y1bW1XUWlTbmF0ZmR6RUVteFFqRnJWUgovdVRuM3BzNjF5bkwxWlhpU29wdVRzcWNydG1HL2t0cWNmOWQwWGVhTzVxcDkyQVlxWTN2YlBYRENPdDJTZmdMCklTQjY2Wi81aEllWHUxUnZha0d4eFdIZmhtdXFCcVVsYW5vVThWNlpaWjB4Ky9qRGJaOUJKU1RHUTRaUk0rWlYKODJVanRzSVE2M2ppZVZBVGsxT3dQZTlxSGpNUW5zTlByYjVtQVdJcnhtUXhJazhaOE9xZ0RsdHl5QnhSSHF2OApNTUdGbVpNK2xRK1phODVRZlBQUW1ULytKMVd1a20xd0tOV2ZyL0hLd3J4REtweUxVenIxYk1VUmlMaVI5M0NxCjlINnFFdmMzcVFEcEJsZGI5U3ZnaitreE03N2QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=' | base64 -d > public_key
          cat public_key
          if [ -z "${TAURI_PRIVATE_KEY}" ]; then echo "TAURI_PRIVATE_KEY secret is not set" && exit 1; fi
          echo "${TAURI_PRIVATE_KEY}" >secret_value
          openssl smime -encrypt -aes256 -in secret_value -binary -outform DEM -out encrypted_secret_value public_key
          cat encrypted_secret_value | base64 -w 0
