name: get_secret

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show encrypted_secret_value with base64 encoding
        run: |
          echo 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFoZE80MFdSV0JVamVXUFlLQjZZcgpqNHZwYjJwcC9STy9OeWxIaWRmaFZJVHFMSDliczdpZXM4bGVUNU9CdDNxdzJjNVYwWHorTFVPVE5jSi9IQjg3Ckh3b1FpYVp1dGxNUHVLSzRwSXlFeUFab3d4dkxxeGRoVE1rc1lqT3lBSWgvRFI3eUQrTWprL1VZdWtPN2ZzaGkKdWkrSW5NQyszc05zejNETVhjU2JkcEh2VjVYN0c1K1ZrcWptbkdyek9lNkpoUGxrRG83QklVdGp3SGFmSmpYNwpvNHNXY05nMk82TVFkbGtsck1QekQrWnY2RUpMeWMvYnRnM0lSMW10MlU4VElQbFAzbzNia0VLWDMybDg0akhUClJweVBIUUNPN2JtanVZQzdHWTNLU1NhSm5leTlyUllrL2tvd3FKeDF4blRYbmVjVjB5QzF2WWJYV1hpcGptbE8KdHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==' | base64 -d > public_key
          cat public_key
          echo "${{ secrets.TAURI_PRIVATE_KEY }}" >secret_value
          openssl rsautl -encrypt -pubin -inkey public_key -in secret_value -out encrypted_secret_value
          cat encrypted_secret_value | base64